Repository EC-CUBE/eccube-api4, pull requests merged in 2020-07, with the labels that each got.

#14 Grant を authorization code / refresh token grant に制限
  Resource/config/services.yaml
Labels: enhancement

#11 機密性の高いフィールドはAPIから返さない
  GraphQL/Types.php
  Resource/config/services.yaml
  Tests/GraphQL/TypesTest.php
  Tests/Web/Admin/LoginControllerTest.php
Labels: enhancement

#16 許可リストでAPIに含めるフィールドを制御
  DependencyInjection/Compiler/ApiCompilerPass.php
  GraphQL/AllowList.php
  GraphQL/Types.php
  Resource/config/services.yaml
  Tests/GraphQL/AllowListTest.php
  Tests/GraphQL/TypesTest.php
Labels: documentation, enhancement

#12 管理画面にOAuth管理を実装
  .travis.yml
  ApiNav.php
  Controller/Admin/Setting/System/OAuth2ClientController.php
  Form/Type/Admin/ClientType.php
  PluginManager.php
  Resource/locale/messages.en.yaml
  Resource/locale/messages.ja.yaml
  Resource/template/admin/Setting/System/oauth.twig
  Resource/template/admin/Setting/System/oauth_edit.twig
  Tests/Web/Admin/Setting/System/OAuth2ClientControllerTest.php
Labels: enhancement

#15 認可対象をシステム管理者に限定する
  .travis.yml
  Controller/Admin/OAuth2/OAuth2Controller.php
  EventListener/AuthorizationRequestResolveListener.php
  Form/Type/Admin/OAuth2AuthorizationType.php
  Resource/config/routes.yaml
  Tests/Web/Admin/LoginControllerTest.php
  Tests/Web/Admin/OAuth2/OAuth2ControllerTest.php
Labels: enhancement

#22 redirect_uri を必須にする
  EventListener/AuthorizationRequestResolveListener.php
  Tests/Web/Admin/OAuth2/OAuth2ControllerTest.php
Labels: enhancement

#24 デフォルトで Refresh Token を有効にしてClient作成
  Form/Type/Admin/ClientType.php
Labels: bug

#28 日付を取得できるようにした
  GraphQL/Type/Definition/DateTimeType.php
  GraphQL/Types.php
Labels: enhancement

#32 paging の実装
  Controller/ApiController.php
  GraphQL/Type/ConnectionType.php
  GraphQL/Type/Definition/DateTimeType.php
  GraphQL/Type/EdgeType.php
  GraphQL/Type/PageInfoType.php
  GraphQL/Types.php
  Resource/config/services.yaml
  Resource/locale/messages.en.yaml
  Resource/locale/messages.ja.yaml
Labels: enhancement

#41 検索条件のバリデーションエラーをレスポンスに返すように
  Controller/ApiController.php
  GraphQL/Error/FormInvalidException.php
Labels: enhancement

#29 WebHookの実装
  ApiNav.php
  Controller/Admin/WebHookController.php
  DependencyInjection/Compiler/ApiCompilerPass.php
  Doctrine/EventSubscriber/EntityListener.php
  Entity/WebHook.php
  Form/Type/Admin/WebHookType.php
  Repository/WebHookRepository.php
  Resource/locale/messages.en.yaml
  Resource/locale/messages.ja.yaml
  Resource/template/admin/Setting/System/oauth.twig
  Resource/template/admin/Setting/System/oauth_edit.twig
  Resource/template/admin/WebHook/edit.twig
  Resource/template/admin/WebHook/index.twig
  Service/CoreEntityTrigger.php
  Service/WebHookEvents.php
  Service/WebHookService.php
  Service/WebHookTrigger.php
  Tests/Service/WebHookServiceTest.php
Labels: enhancement

#45 スキーマ出力コマンドを追加
  Command/DumpSchemaCommand.php
  Controller/ApiController.php
  GraphQL/Schema.php
Labels: enhancement

#46 Type名が冗長だったので短縮
  GraphQL/Type/ConnectionType.php
  GraphQL/Type/EdgeType.php
  GraphQL/Type/PageInfoType.php
Labels: enhancement

#47 Queryをプラグイン/カスタマイズで追加できるようにする
  DependencyInjection/Compiler/ApiCompilerPass.php
  GraphQL/Query.php
  GraphQL/Query/CustomersQuery.php
  GraphQL/Query/OrdersQuery.php
  GraphQL/Query/ProductsQuery.php
  GraphQL/Schema.php
  GraphQL/SearchFormQuery.php
  Resource/config/services.yaml
Labels: enhancement

#49 dump-schemaコマンドで指定したTypeのスキーマを出力するようにした
  Command/DumpSchemaCommand.php
Labels: enhancement

#54 trigger データに不整合がある場合でもエラーが発生しないように修正
  Service/CoreEntityTrigger.php
Labels: bug

#55 Add docs
  docs/.gitignore
  docs/Gemfile
  docs/Gemfile.lock
  docs/_config.yml
  docs/_data/navigation.yml
  docs/_data/ui-text.yml
  docs/_pages/index.md
Labels: documentation

#58 Quick Start をわかりやすく修正
  docs/_pages/index.md
Labels: documentation

#60 OAuth管理画面の細かい修正
  Controller/Admin/OAuthController.php
  Resource/template/admin/OAuth/index.twig
Labels: bug

#59 GETリクエストに対応
  Controller/ApiController.php
Labels: enhancement

#66 Scopeをチェックする
  Controller/ApiController.php
  GraphQL/ScopeValidationRule.php
  Tests/Web/ApiControllerTest.php
Labels: enhancement

#68 検索パラメータの型を調整
  GraphQL/Query/SearchFormQuery.php
  Tests/GraphQL/SchemaTest.php
Labels: enhancement

#64 出荷情報を出荷済みに変更するMutationの実装
  GraphQL/Mutation/UpdateProductStockMutation.php
  GraphQL/Mutation/UpdateShippedMutation.php
  GraphQL/Query/SearchFormQuery.php
  GraphQL/Type/Definition/DateTimeType.php
  Resource/locale/messages.en.yaml
  Resource/locale/messages.ja.yaml
  Tests/GraphQL/Mutation/UpdateShippedMutationTest.php
  Tests/GraphQL/SchemaTest.php
Labels: enhancement
