Repository EC-CUBE/eccube-api4, pull requests merged in 2020-08, with the labels that each got.

#74 デフォルトの鍵保管場所を変更
  Resource/config/services.yaml
Labels: documentation

#73 Query のドキュメント叩き台を追加
  docs/_pages/index.md
  docs/_pages/mutation/product_stock.md
  docs/_pages/mutation/update_shipped.md
  docs/_pages/query/customers.md
  docs/_pages/query/orders.md
  docs/_pages/query/products.md
Labels: documentation

#72 ReadmeとDocを更新
  LICENSE
  README.md
  docs/_config.yml
  docs/_pages/index.md
Labels: documentation

#76 商品在庫の更新のドキュメントを追加
  docs/_pages/mutation/product_stock.md
Labels: documentation

#78 認可リクエスト画面の改善
  EventListener/AuthorizationRequestResolveListener.php
  Form/Type/Admin/OAuth2AuthorizationType.php
  Resource/locale/messages.en.yaml
  Resource/locale/messages.ja.yaml
  Resource/template/admin/OAuth/authorization.twig
  Tests/Web/Admin/OAuth2Bundle/AuthorizationControllerTest.php
Labels: enhancement

#75 OAuth管理画面の改善
  Controller/Admin/OAuthController.php
  Form/Type/Admin/ClientType.php
  Resource/locale/messages.en.yaml
  Resource/locale/messages.ja.yaml
  Resource/template/admin/OAuth/edit.twig
  Resource/template/admin/OAuth/index.twig
  Tests/Web/Admin/OAuthControllerTest.php
Labels: enhancement

#79 Mutation updateShippedの概要と実行例を追加
  docs/_pages/mutation/update_shipped.md
Labels: documentation

#80 DateTime型のargsを型変換するように修正
  GraphQL/Query/SearchFormQuery.php
  GraphQL/Type/Definition/DateTimeType.php
  Tests/GraphQL/SchemaTest.php
Labels: bug

#83 スキーマについてのドキュメントを追加
  docs/_pages/index.md
  docs/_pages/schema.md
Labels: documentation

#81 GraphiQL を組み込み
  ApiNav.php
  Controller/Admin/GraphiQLController.php
  Resource/locale/messages.en.yaml
  Resource/locale/messages.ja.yaml
  Resource/template/admin/OAuth/graphiql.twig
Labels: enhancement

#82 取得可能なデータの追加とQuery/Mutationの追加のドキュメントを追加
  docs/_pages/customize/allow_list.md
  docs/_pages/customize/query.md
  docs/_pages/index.md
Labels: documentation

#86 Fix argument mismatch.
  Service/WebHookService.php
Labels: bug

#91 doc4.ec-cube.net のテーマに合わせる
  docs/_config.yml
  docs/_data/navigation.yml
  docs/_pages/authZ_code_grant.md
  docs/_pages/customize/allow_list.md
  docs/_pages/customize/query.md
  docs/_pages/index.md
  docs/_pages/mutation/product_stock.md
  docs/_pages/mutation/update_shipped.md
  docs/_pages/query/customers.md
  docs/_pages/query/orders.md
  docs/_pages/query/products.md
  docs/_pages/schema.md
  docs/assets/css/main.scss
Labels: documentation

#87 GraphiQL に管理画面のメニュー,ヘッダ,フッターをつける
  Resource/template/admin/OAuth/graphiql.twig
Labels: enhancement

#90 webhookに関するドキュメントを追加
  docs/_pages/index.md
  docs/_pages/webhook.md
Labels: documentation

#92 現在のバージョンでの制限事項
  docs/_pages/index.md
Labels: documentation
